# Generated by Django 6.0.8 on 2026-08-26 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认课时包', max_length=128, verbose_name='课时包名称')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='总课时')),
                ('used_sessions', models.PositiveIntegerField(default=0, verbose_name='已消耗课时')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '课时包',
                'verbose_name_plural': '课时包',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='调整量（正负）')),
                ('reason', models.CharField(max_length=255, verbose_name='调整原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='courses.coursepackage', verbose_name='课时包')),
            ],
            options={
                'verbose_name': '课时调整',
                'verbose_name_plural': '课时调整',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coursepackage',
            index=models.Index(fields=['therapist', 'customer'], name='idx_coursepkg_therapist'),
        ),
    ]
