# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseadjustment',
            table='course_adjustments',
        ),
        migrations.AlterModelTable(
            name='coursepackage',
            table='course_packages',
        ),
    ]
