# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseadjustment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseadjustment',
            table='tb_course_adjustments',
        ),
        migrations.AlterModelTable(
            name='coursepackage',
            table='tb_course_packages',
        ),
    ]
