# Generated by Django 6.0.8 on 2026-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseadjustment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadjustment',
            name='delta',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='调整量（正负，支持半课 0.5）'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='total_sessions',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='总课时'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='used_sessions',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='已消耗课时'),
        ),
    ]
