# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseadjustment_source'),
        ('customers', '0004_alter_customer_therapist'),
        ('schedules', '0009_rename_course_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadjustment',
            name='course_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_adjustments', to='schedules.coursesession', verbose_name='来源排课'),
        ),
        migrations.AlterField(
            model_name='courseadjustment',
            name='package',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='courses.coursepackage', verbose_name='课时包'),
        ),
        migrations.AlterField(
            model_name='courseadjustment',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
    ]
