# Generated by Django 6.0.8 on 2026-08-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(verbose_name='训练日期')),
                ('customer_feedback', models.TextField(blank=True, default='', verbose_name='客户感受')),
                ('therapist_observation', models.TextField(blank=True, default='', verbose_name='康复师观察')),
                ('next_plan', models.TextField(blank=True, default='', verbose_name='下次计划')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='schedules.coursesession', verbose_name='关联课程')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '训练记录',
                'verbose_name_plural': '训练记录',
                'ordering': ['-training_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=128, verbose_name='动作名称')),
                ('sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='组数')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='次数')),
                ('weight', models.CharField(blank=True, default='', max_length=32, verbose_name='负荷/重量')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（秒）')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('training_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.trainingrecord', verbose_name='训练记录')),
            ],
            options={
                'verbose_name': '训练动作',
                'verbose_name_plural': '训练动作',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['therapist', 'customer'], name='idx_tr_therapist_customer'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['customer', 'training_date'], name='idx_tr_customer_date'),
        ),
    ]
