# Generated by Django 6.0.8 on 2026-08-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='家庭训练', max_length=128, verbose_name='标题')),
                ('frequency', models.CharField(blank=True, default='', max_length=64, verbose_name='频率')),
                ('note', models.TextField(blank=True, default='', verbose_name='注意事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_training_plans', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '家庭训练计划',
                'verbose_name_plural': '家庭训练计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=128, verbose_name='动作名称')),
                ('sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='组数')),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='次数')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（秒）')),
                ('frequency', models.CharField(blank=True, default='', max_length=64, verbose_name='频率')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='注意事项')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.hometrainingplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '家庭训练动作',
                'verbose_name_plural': '家庭训练动作',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='hometrainingplan',
            index=models.Index(fields=['therapist', 'customer'], name='idx_hometrain_therapist'),
        ),
    ]
