# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_hometrainingplan_hometrainingexercise_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hometrainingexercise',
            table='home_training_exercises',
        ),
        migrations.AlterModelTable(
            name='hometrainingplan',
            table='home_training_plans',
        ),
        migrations.AlterModelTable(
            name='trainingexercise',
            table='training_exercises',
        ),
        migrations.AlterModelTable(
            name='trainingrecord',
            table='training_records',
        ),
    ]
