# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_hometrainingexercise_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hometrainingexercise',
            table='tb_home_training_exercises',
        ),
        migrations.AlterModelTable(
            name='hometrainingplan',
            table='tb_home_training_plans',
        ),
        migrations.AlterModelTable(
            name='trainingexercise',
            table='tb_training_exercises',
        ),
        migrations.AlterModelTable(
            name='trainingrecord',
            table='tb_training_records',
        ),
    ]
