# Generated by Django 6.0.8 on 2026-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_hometrainingexercise_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认'),
        ),
    ]
