# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        ('schedules', '0010_alter_coursesession_customer_and_more'),
        ('training', '0006_remove_trainingrecord_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometrainingexercise',
            name='plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.hometrainingplan', verbose_name='所属计划'),
        ),
        migrations.AlterField(
            model_name='hometrainingplan',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='home_training_plans', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='hometrainingplan',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='home_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='trainingexercise',
            name='training_record',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.trainingrecord', verbose_name='训练记录'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='course_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='schedules.coursesession', verbose_name='关联课程'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
    ]
