# Generated by Django 6.0.8 on 2026-09-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aidraft_assessment_aidraft_draft_type_and_more'),
        ('assistant_tasks', '0002_assistantrun_chk_asrun_attempt_pos_and_more'),
        ('customers', '0004_alter_customer_therapist'),
        ('training', '0008_trainingrecord_unique_course_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='activity_type',
            field=models.CharField(choices=[('exercise', '训练动作'), ('therapy', '康复治疗'), ('massage', '按摩')], default='exercise', max_length=16, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='单位'),
        ),
        migrations.CreateModel(
            name='TrainingRecordBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='子项顺序')),
                ('source_message', models.TextField(blank=True, default='', verbose_name='原始输入')),
                ('customer_name_hint', models.CharField(blank=True, default='', max_length=64, verbose_name='客户姓名提示')),
                ('parsed_payload', models.JSONField(blank=True, default=dict, verbose_name='结构化训练内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('searching_customer', '查找客户中'), ('waiting_customer', '等待客户确认'), ('waiting_draft', '等待草稿确认'), ('saving', '保存中'), ('completed', '已完成'), ('skipped', '已跳过'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=24, verbose_name='子项状态')),
                ('confirmation_key', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='正式保存幂等键')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ai_draft', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='ai.aidraft', verbose_name='AI 草稿')),
                ('assistant_task', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='assistant_tasks.assistanttask', verbose_name='父级批量任务')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_batch_items', to='customers.customer', verbose_name='客户')),
                ('training_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='training.trainingrecord', verbose_name='正式训练记录')),
            ],
            options={
                'verbose_name': '训练批量子项',
                'verbose_name_plural': '训练批量子项',
                'db_table': 'tb_training_record_batch_items',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['assistant_task', 'status'], name='idx_trb_item_task_status'), models.Index(fields=['assistant_task', 'sequence'], name='idx_trb_item_task_seq')],
                'constraints': [models.UniqueConstraint(fields=('assistant_task', 'sequence'), name='uniq_trb_item_task_sequence')],
            },
        ),
    ]
