# Generated by Django 6.0.8 on 2026-08-26 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='动作名称')),
                ('body_part', models.CharField(blank=True, default='', max_length=64, verbose_name='训练部位')),
                ('description', models.TextField(blank=True, default='', verbose_name='动作说明')),
                ('precautions', models.TextField(blank=True, default='', verbose_name='注意事项')),
                ('contraindications', models.TextField(blank=True, default='', verbose_name='禁忌')),
                ('is_official', models.BooleanField(default=False, verbose_name='是否官方动作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '训练动作',
                'verbose_name_plural': '训练动作',
                'ordering': ['-is_official', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, verbose_name='别名')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='exercises.exercise', verbose_name='动作')),
            ],
            options={
                'verbose_name': '动作别名',
                'verbose_name_plural': '动作别名',
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['therapist'], name='idx_exercise_therapist'),
        ),
    ]
