# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='exercisealias',
            table='exercise_aliases',
        ),
    ]
