# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_table_alter_exercisealias_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='tb_exercises',
        ),
        migrations.AlterModelTable(
            name='exercisealias',
            table='tb_exercise_aliases',
        ),
    ]
