# Generated by Django 6.0.8 on 2026-08-29 00:45

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CustomerKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medical', '医疗与康复背景'), ('safety', '安全限制'), ('recovery', '康复过程'), ('preference', '个体化偏好'), ('other', '其他')], default='other', max_length=16, verbose_name='分类')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('source', models.CharField(choices=[('manual', '康复师手动'), ('ai_confirmed', 'AI 建议确认'), ('training', '训练记录'), ('assessment', '评估'), ('conversation', 'AI 对话')], default='manual', max_length=16, verbose_name='来源')),
                ('importance', models.CharField(choices=[('high', '高'), ('normal', '普通')], default='normal', max_length=10, verbose_name='重要级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True, verbose_name='向量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户知识条目',
                'verbose_name_plural': '客户知识条目',
                'db_table': 'tb_customer_knowledge_items',
                'ordering': ['-importance', 'category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='拟写入内容')),
                ('category', models.CharField(choices=[('medical', '医疗与康复背景'), ('safety', '安全限制'), ('recovery', '康复过程'), ('preference', '个体化偏好'), ('other', '其他')], default='other', max_length=16, verbose_name='建议分类')),
                ('source_ref', models.CharField(blank=True, default='', max_length=255, verbose_name='来源说明')),
                ('suggested_at', models.DateTimeField(auto_now_add=True, verbose_name='建议时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝')], default='pending', max_length=12, verbose_name='状态')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_candidates', to='customers.customer', verbose_name='客户')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_decided', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='knowledge.customerknowledgeitem', verbose_name='确认生成的知识')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_candidates', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '知识候选',
                'verbose_name_plural': '知识候选',
                'db_table': 'tb_knowledge_candidates',
                'ordering': ['-suggested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerknowledgeitem',
            index=models.Index(fields=['therapist', 'customer'], name='idx_knowledge_therapist'),
        ),
        migrations.AddIndex(
            model_name='customerknowledgeitem',
            index=models.Index(fields=['customer', 'is_active'], name='idx_knowledge_customer_active'),
        ),
        migrations.AddIndex(
            model_name='knowledgecandidate',
            index=models.Index(fields=['therapist', 'customer'], name='idx_kc_therapist'),
        ),
        migrations.AddIndex(
            model_name='knowledgecandidate',
            index=models.Index(fields=['status'], name='idx_kc_status'),
        ),
    ]
