# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerknowledgeitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='customerknowledgeitem',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='customerknowledgeitem',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='customerknowledgeitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_candidates', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='decided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_decided', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='knowledge.customerknowledgeitem', verbose_name='确认生成的知识'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_candidates', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
    ]
