# Generated by Django 6.0.8 on 2026-08-30 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        ('knowledge', '0002_alter_customerknowledgeitem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='可信度'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='confirmed_by_user',
            field=models.BooleanField(default=True, verbose_name='是否人工确认'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效时间'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='失效时间'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='importance_score',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='重要度（1-5）'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近确认时间'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='memory_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='记忆键'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='memory_type',
            field=models.CharField(choices=[('preference', '训练偏好'), ('dislike', '不喜欢'), ('communication', '沟通习惯'), ('habit', '训练或生活习惯'), ('goal', '长期目标'), ('concern', '顾虑'), ('pattern', '长期观察规律'), ('background', '康复相关背景'), ('therapist_observation', '康复师长期观察'), ('other', '其他')], default='other', max_length=32, verbose_name='记忆类型'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='normalized_value',
            field=models.TextField(blank=True, default='', verbose_name='标准化内容'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='来源标识'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='source_message_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='来源消息标识'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='status',
            field=models.CharField(choices=[('candidate', '待确认'), ('active', '生效'), ('superseded', '已替代'), ('expired', '已停用'), ('deleted', '已删除')], default='active', max_length=12, verbose_name='记忆状态'),
        ),
        migrations.AddField(
            model_name='customerknowledgeitem',
            name='supersedes_memory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='knowledge.customerknowledgeitem', verbose_name='替代的旧记忆'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='提取可信度'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='evidence',
            field=models.TextField(blank=True, default='', verbose_name='提取证据'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='importance_score',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='建议重要度（1-5）'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='memory_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='建议记忆键'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='memory_type',
            field=models.CharField(choices=[('preference', '训练偏好'), ('dislike', '不喜欢'), ('communication', '沟通习惯'), ('habit', '训练或生活习惯'), ('goal', '长期目标'), ('concern', '顾虑'), ('pattern', '长期观察规律'), ('background', '康复相关背景'), ('therapist_observation', '康复师长期观察'), ('other', '其他')], default='other', max_length=32, verbose_name='建议记忆类型'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='normalized_value',
            field=models.TextField(blank=True, default='', verbose_name='建议标准化内容'),
        ),
        migrations.AddIndex(
            model_name='customerknowledgeitem',
            index=models.Index(fields=['customer', 'status'], name='idx_memory_customer_status'),
        ),
    ]
