# Generated by Django 6.0.8 on 2026-08-30 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_customerknowledgeitem_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerknowledgeitem',
            name='importance_score',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重要度（1-5）'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='importance_score',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='建议重要度（1-5）'),
        ),
    ]
