# Generated by Django 6.0.8 on 2026-08-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('knowledge', '0004_alter_customerknowledgeitem_importance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecandidate',
            name='conflict_memory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_candidates', to='knowledge.customerknowledgeitem', verbose_name='冲突的有效记忆'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='conflict_type',
            field=models.CharField(choices=[('none', '无冲突'), ('conflict', '内容冲突'), ('conditional', '适用条件不同'), ('supplement', '补充信息')], default='none', max_length=16, verbose_name='与现有记忆的关系'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='resolution_action',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='处理方式'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='source_conversation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_candidates', to='conversations.conversation', verbose_name='来源会话'),
        ),
        migrations.AddField(
            model_name='knowledgecandidate',
            name='source_message',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_candidates', to='conversations.message', verbose_name='来源消息'),
        ),
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝'), ('deferred', '暂缓处理')], default='pending', max_length=12, verbose_name='状态'),
        ),
    ]
