# Generated by Django 6.0.8 on 2026-08-30 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_episode_analyzed_through_message_id'),
        ('customers', '0004_alter_customer_therapist'),
        ('knowledge', '0005_knowledgecandidate_conflict_memory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_key', models.CharField(max_length=120, verbose_name='事件键')),
                ('title', models.CharField(max_length=160, verbose_name='主题')),
                ('summary', models.TextField(verbose_name='讨论摘要')),
                ('key_points', models.JSONField(blank=True, default=list, verbose_name='关键点')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='讨论决定')),
                ('next_actions', models.JSONField(blank=True, default=list, verbose_name='下一步行动')),
                ('importance_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重要度（1-5）')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='可信度')),
                ('status', models.CharField(choices=[('candidate', '待确认'), ('active', '生效'), ('rejected', '已拒绝'), ('deleted', '已删除')], default='candidate', max_length=12, verbose_name='状态')),
                ('source_start_message_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='来源起始消息 ID')),
                ('source_end_message_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='来源结束消息 ID')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conversation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_episodes', to='conversations.conversation', verbose_name='来源会话')),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='memory_episodes', to='customers.customer', verbose_name='客户')),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_episodes_decided', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('therapist', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='memory_episodes', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'db_table': 'tb_memory_episodes',
                'ordering': ['-importance_score', '-created_at'],
                'indexes': [models.Index(fields=['therapist', 'customer', 'status'], name='idx_episode_scope'), models.Index(fields=['customer', 'created_at'], name='idx_episode_customer_time')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'episode_key'), name='uq_episode_conversation_key')],
            },
        ),
    ]
