# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_therapist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='therapist',
            table='tb_therapists',
        ),
    ]
