# Generated by Django 6.0.8 on 2026-08-26 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('failed', '解析失败')], default='pending', max_length=12, verbose_name='状态')),
                ('input_text', models.TextField(verbose_name='用户原始输入')),
                ('ai_result', models.JSONField(blank=True, default=dict, verbose_name='AI 初始结果')),
                ('confirmed_result', models.JSONField(blank=True, default=dict, verbose_name='确认结果')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='customers.customer', verbose_name='关联客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': 'AI 草稿',
                'verbose_name_plural': 'AI 草稿',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'status'], name='idx_ai_therapist_status')],
            },
        ),
    ]
