# Generated by Django 6.0.8 on 2026-08-27 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('customers', '0001_initial'),
        ('training', '0002_hometrainingplan_hometrainingexercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='风险等级')),
                ('evidence', models.TextField(blank=True, default='', verbose_name='发现依据')),
                ('suggested_action', models.CharField(choices=[('pause', '暂停'), ('review', '复查'), ('check', '检查'), ('refer', '考虑转诊')], default='check', max_length=10, verbose_name='建议动作')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
                ('outcome', models.CharField(blank=True, default='', max_length=255, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
                ('training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='training.trainingrecord', verbose_name='关联训练记录')),
            ],
            options={
                'verbose_name': '风险提醒',
                'verbose_name_plural': '风险提醒',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'customer'], name='idx_risk_therapist')],
            },
        ),
    ]
