# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_riskalert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aidraft',
            table='ai_drafts',
        ),
        migrations.AlterModelTable(
            name='riskalert',
            table='risk_alerts',
        ),
    ]
