# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aidraft_table_alter_riskalert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aidraft',
            table='tb_ai_drafts',
        ),
        migrations.AlterModelTable(
            name='riskalert',
            table='tb_risk_alerts',
        ),
    ]
