# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aidraft_table_alter_riskalert_table'),
        ('customers', '0004_alter_customer_therapist'),
        ('training', '0006_remove_trainingrecord_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidraft',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='customers.customer', verbose_name='关联客户'),
        ),
        migrations.AlterField(
            model_name='aidraft',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='riskalert',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='riskalert',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='riskalert',
            name='training_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='training.trainingrecord', verbose_name='关联训练记录'),
        ),
    ]
