# Generated by Django 6.0.8 on 2026-08-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_aidraft_customer_alter_aidraft_therapist_and_more'),
        ('assistant_tasks', '0001_initial'),
        ('training', '0008_trainingrecord_unique_course_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidraft',
            name='assistant_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='assistant_tasks.assistanttask', verbose_name='统一助手任务'),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='confirmation_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='确认幂等键'),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='training_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='training.trainingrecord', verbose_name='正式训练记录'),
        ),
    ]
