# Generated by Django 6.0.8 on 2026-09-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aidraft_assistant_task_aidraft_confirmation_key_and_more'),
        ('assessments', '0006_guided_assessment'),
        ('followups', '0004_alter_followuptask_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidraft',
            name='assessment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='assessments.assessment', verbose_name='正式评估'),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='draft_type',
            field=models.CharField(choices=[('training_record', '训练补记'), ('assessment', '评估'), ('training_revision', '训练记录修订'), ('followup', '随访')], default='training_record', max_length=24, verbose_name='草稿类型'),
        ),
        migrations.AddField(
            model_name='aidraft',
            name='followup',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_drafts', to='followups.followuptask', verbose_name='正式随访'),
        ),
    ]
