# Generated by Django 6.0.8 on 2026-09-09 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aidraft_assessment_aidraft_draft_type_and_more'),
        ('customers', '0005_customeralias'),
        ('training', '0009_trainingexercise_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskalert',
            name='rule_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='触发规则代码'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['therapist', 'customer', 'rule_code'], name='idx_risk_therapist_rule'),
        ),
    ]
