# Generated by Django 6.0.8 on 2026-08-31 23:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_conversation_episode_analyzed_through_message_id'),
        ('customers', '0004_alter_customer_therapist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.CharField(blank=True, default='', max_length=100, verbose_name='技能代码')),
                ('task_type', models.CharField(blank=True, default='', max_length=64, verbose_name='任务类型')),
                ('invocation_mode', models.CharField(blank=True, default='manual', max_length=32, verbose_name='调用模式')),
                ('origin', models.CharField(blank=True, default='', max_length=64, verbose_name='任务来源')),
                ('context_resource_type', models.CharField(blank=True, default='', max_length=32, verbose_name='上下文资源类型')),
                ('context_resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='上下文资源标识')),
                ('business_key', models.CharField(blank=True, default='', max_length=255, verbose_name='业务复用键')),
                ('client_request_id', models.CharField(blank=True, default='', max_length=128, verbose_name='客户端请求幂等键')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('waiting_user', '等待用户输入'), ('waiting_confirmation', '等待确认'), ('blocked', '已阻塞'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='任务状态')),
                ('current_step', models.CharField(blank=True, default='', max_length=128, verbose_name='当前步骤')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='待补充字段')),
                ('state_data', models.JSONField(blank=True, default=dict, verbose_name='任务状态数据')),
                ('draft_resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='草稿资源类型')),
                ('draft_resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='草稿资源标识')),
                ('result_resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='结果资源类型')),
                ('result_resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='结果资源标识')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='任务版本')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近活动时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conversation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_tasks', to='conversations.conversation', verbose_name='会话')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_tasks', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_tasks', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '助手任务',
                'verbose_name_plural': '助手任务',
                'db_table': 'tb_assistant_tasks',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.CharField(blank=True, default='', max_length=128, verbose_name='本次执行幂等键')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='执行尝试次数')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '超时')], default='queued', max_length=20, verbose_name='执行状态')),
                ('provider', models.CharField(blank=True, default='', max_length=64, verbose_name='模型供应商')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='模型名称')),
                ('input_summary', models.JSONField(blank=True, default=dict, verbose_name='执行输入脱敏摘要')),
                ('output_summary', models.JSONField(blank=True, default=dict, verbose_name='执行输出脱敏摘要')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trigger_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_runs', to='conversations.message', verbose_name='触发消息')),
                ('task', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='assistant_tasks.assistanttask', verbose_name='助手任务')),
            ],
            options={
                'verbose_name': '助手执行',
                'verbose_name_plural': '助手执行',
                'db_table': 'tb_assistant_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='变更前状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='变更后状态')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_task_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assistant_tasks.assistantrun', verbose_name='关联执行')),
                ('task', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assistant_tasks.assistanttask', verbose_name='助手任务')),
            ],
            options={
                'verbose_name': '任务事件',
                'verbose_name_plural': '任务事件',
                'db_table': 'tb_task_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='调用顺序')),
                ('tool_name', models.CharField(max_length=128, verbose_name='工具名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='工具执行状态')),
                ('input_summary', models.JSONField(blank=True, default=dict, verbose_name='工具输入脱敏摘要')),
                ('output_summary', models.JSONField(blank=True, default=dict, verbose_name='工具输出脱敏摘要')),
                ('is_write', models.BooleanField(default=False, verbose_name='是否写操作')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='是否需要确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('result_resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='结果资源类型')),
                ('result_resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='结果资源标识')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tool_executions', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('run', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='assistant_tasks.assistantrun', verbose_name='助手执行')),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='assistant_tasks.assistanttask', verbose_name='助手任务')),
            ],
            options={
                'verbose_name': '工具执行',
                'verbose_name_plural': '工具执行',
                'db_table': 'tb_tool_executions',
                'ordering': ['run', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assistanttask',
            index=models.Index(fields=['therapist', 'status', 'updated_at'], name='idx_astask_scope_status'),
        ),
        migrations.AddIndex(
            model_name='assistanttask',
            index=models.Index(fields=['therapist', 'customer', 'status'], name='idx_astask_customer_status'),
        ),
        migrations.AddIndex(
            model_name='assistanttask',
            index=models.Index(fields=['therapist', 'business_key'], name='idx_astask_business_key'),
        ),
        migrations.AddIndex(
            model_name='assistanttask',
            index=models.Index(fields=['therapist', 'client_request_id'], name='idx_astask_client_request'),
        ),
        migrations.AddConstraint(
            model_name='assistanttask',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('therapist', 'client_request_id'), name='uniq_astask_client_request'),
        ),
        migrations.AddConstraint(
            model_name='assistanttask',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('business_key', ''), _negated=True), ('customer__isnull', False), ('status__in', ['pending', 'running', 'waiting_user', 'waiting_confirmation', 'blocked', 'failed'])), fields=('therapist', 'customer', 'business_key'), name='uniq_astask_active_biz_customer'),
        ),
        migrations.AddConstraint(
            model_name='assistanttask',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('business_key', ''), _negated=True), ('customer__isnull', True), ('status__in', ['pending', 'running', 'waiting_user', 'waiting_confirmation', 'blocked', 'failed'])), fields=('therapist', 'business_key'), name='uniq_astask_active_biz_general'),
        ),
        migrations.AddIndex(
            model_name='assistantrun',
            index=models.Index(fields=['task', 'status'], name='idx_asrun_task_status'),
        ),
        migrations.AddIndex(
            model_name='assistantrun',
            index=models.Index(fields=['task', 'attempt'], name='idx_asrun_task_attempt'),
        ),
        migrations.AddConstraint(
            model_name='assistantrun',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('task', 'client_request_id'), name='uniq_asrun_client_request'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', 'created_at'], name='idx_taskevent_task_time'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', 'event_type'], name='idx_taskevent_task_type'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['run', 'status'], name='idx_toolexec_run_status'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['task', 'status'], name='idx_toolexec_task_status'),
        ),
    ]
