# Generated by Django 6.0.8 on 2026-09-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assistantrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1)), name='chk_asrun_attempt_pos'),
        ),
        migrations.AddConstraint(
            model_name='assistantrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out'])), name='chk_asrun_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='assistanttask',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='chk_astask_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='assistanttask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'waiting_user', 'waiting_confirmation', 'blocked', 'completed', 'failed', 'cancelled', 'expired'])), name='chk_astask_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 0)), name='chk_toolexec_sequence_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'succeeded', 'failed', 'cancelled'])), name='chk_toolexec_status_valid'),
        ),
    ]
