# Generated by Django 6.0.8 on 2026-08-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('confirm', '确认'), ('login', '登录'), ('logout', '登出')], max_length=20, verbose_name='动作')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='操作前快照')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='操作后快照')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_audit_content'), models.Index(fields=['created_at'], name='idx_audit_created')],
            },
        ),
    ]
