# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='tb_audit_logs',
        ),
    ]
