"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-development-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [host for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.common',
    'apps.accounts',
    'apps.therapists',
    'apps.customers',
    'apps.schedules',
    'apps.assessments',
    'apps.rehab',
    'apps.training',
    'apps.exercises',
    'apps.courses',
    'apps.followups',
    'apps.audit',
    'apps.ai',
    'apps.conversations',
    'apps.knowledge',
    'apps.assistant_tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "retrue"),
        "USER": os.getenv("POSTGRES_USER", "retrue"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "retrue"),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# ============================================================
# AI 服务商配置（配置化）
# 通过 .env 选择 AI provider，避免硬编码服务商与密钥。
# AI_API_KEY 为敏感信息，仅存于服务端 .env，禁止提交仓库。
# ============================================================
AI_PROVIDER = os.getenv("AI_PROVIDER", "mock")
AI_API_KEY = os.getenv("AI_API_KEY", "")
AI_MODEL = os.getenv("AI_MODEL", "")
AI_BASE_URL = os.getenv("AI_BASE_URL", "")
AI_TIMEOUT = int(os.getenv("AI_TIMEOUT", "60"))
AI_MAX_TOKENS = int(os.getenv("AI_MAX_TOKENS", "2000"))
# 多 provider 故障转移：JSON 数组字符串，形如
# [{"provider":"deepseek","model":"deepseek-chat"},{"provider":"mock"}]
# 配置后按顺序使用，单一模型调用失败自动切换下一个。
AI_FALLBACK_PROVIDERS = os.getenv("AI_FALLBACK_PROVIDERS", "")
# AI 多模型 yaml 配置文件路径（相对 retrue-server 或绝对路径）。
# 该文件 config.enabled 为 true 时，优先于 AI_FALLBACK_PROVIDERS / AI_PROVIDER。
AI_CONFIG_FILE = os.getenv("AI_CONFIG_FILE", os.path.join(BASE_DIR, "ai_config.yaml"))

# ============================================================
# AI 助理编排（LangGraph）
# LangGraph 只负责对话流程编排，权限、任务状态、正式业务写入和审计仍由
# Django 领域服务统一负责。功能开关用于在编排器故障时一键退回原有
# Conversation + 训练补记流程，不影响已存在的任务继续通过原确认 API 完成。
# ============================================================
AI_ORCHESTRATION_ENABLED = os.getenv("AI_ORCHESTRATION_ENABLED", "true").lower() == "true"
# 单轮对话最多允许的图节点执行次数（含 Tool 调用节点），防止异常环路。
AI_ORCHESTRATION_MAX_STEPS = int(os.getenv("AI_ORCHESTRATION_MAX_STEPS", "8"))
# 单轮对话最多允许的只读 Tool 调用次数。
AI_ORCHESTRATION_MAX_TOOL_CALLS = int(os.getenv("AI_ORCHESTRATION_MAX_TOOL_CALLS", "3"))
# 受控 ReAct 客户分析子图：单回合最多允许的模型决策（decide）次数。
AI_ORCHESTRATION_MAX_REACT_DECISIONS = int(os.getenv("AI_ORCHESTRATION_MAX_REACT_DECISIONS", "3"))

# ============================================================
# Embedding（客户私有知识库 RAG 向量化）
# 使用 Qwen text-embedding-v3，密钥独立于聊天模型，见 .env。
# ============================================================
# embedding provider 类型，当前支持：qwen。
AI_EMBEDDING_PROVIDER = os.getenv("AI_EMBEDDING_PROVIDER", "qwen")
# embedding 模型名，默认 text-embedding-v3（维度 1024）。
AI_EMBEDDING_MODEL = os.getenv("AI_EMBEDDING_MODEL", "text-embedding-v3")
# embedding 服务地址，默认阿里云百炼 OpenAI 兼容端点。
AI_EMBEDDING_BASE_URL = os.getenv(
    "AI_EMBEDDING_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1"
)
# embedding API Key，可复用 QWEN_API_KEY；缺省时回退到 AI_API_KEY。
AI_EMBEDDING_API_KEY = os.getenv("AI_EMBEDDING_API_KEY", "")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# 使用自定义 User 模型，项目初始即定义便于后续扩展
AUTH_USER_MODEL = "accounts.User"

# 统一 API 异常处理
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.SessionAuthentication"],
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    "UNAUTHENTICATED_USER": None,
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    origin for origin in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",") if origin
]

# 允许携带 Cookie 跨域，供 Session 认证使用
CORS_ALLOW_CREDENTIALS = True

# Session + Cookie 认证配置
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:5173").split(",") if origin
]
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"

# ============================================================
# 日志（LOGGING）
# 默认情况下 Django 应用 logger 的 INFO 及以下日志不会输出（root 级别 WARNING）。
# 这里显式配置：项目命名空间日志以 INFO 打到控制台（PyCharm Run 窗口可见），
# 同时写入 retrue-server/logs/app.log 便于翻查。
# 若想关掉文件输出，可设置环境变量 LOG_TO_FILE=false。
# ============================================================
_LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(_LOG_DIR):
    os.makedirs(_LOG_DIR, exist_ok=True)

_APP_LOG_FILE = os.path.join(_LOG_DIR, "app.log")
_LOG_TO_FILE = os.getenv("LOG_TO_FILE", "true").lower() == "true"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": _APP_LOG_FILE,
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
    },
    "loggers": {
        # 项目应用命名空间日志：INFO 及以上可见。
        "apps": {
            "handlers": (["console", "app_file"] if _LOG_TO_FILE else ["console"]),
            "level": os.getenv("APP_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Django 请求访问日志（如 POST /api/... 200 503），INFO 级打印到控制台。
        "django.server": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_SERVER_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
    "root": {
        "level": "WARNING",
        "handlers": ["console"] if not _LOG_TO_FILE else ["console", "app_file"],
    },
}
