# Generated by Django 6.0.8 on 2026-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('pain', '疼痛'), ('strength', '肌力'), ('rom', '活动度'), ('special_test', '特殊测试'), ('functional', '功能动作')], max_length=16, verbose_name='指标类型')),
                ('body_part', models.CharField(blank=True, default='', max_length=64, verbose_name='部位')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评分')),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='满分')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评估指标',
                'verbose_name_plural': '评估指标',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('initial', '首次评估'), ('reassessment', '阶段复评')], default='initial', max_length=16, verbose_name='评估类型')),
                ('assessment_date', models.DateField(verbose_name='评估日期')),
                ('chief_complaint', models.TextField(blank=True, default='', verbose_name='主诉')),
                ('medical_history', models.TextField(blank=True, default='', verbose_name='病史')),
                ('rehab_goal', models.TextField(blank=True, default='', verbose_name='康复目标')),
                ('current_status', models.TextField(blank=True, default='', verbose_name='当前状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '评估',
                'verbose_name_plural': '评估',
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
    ]
