# Generated by Django 6.0.8 on 2026-08-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('rehab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='rehab.rehabplan', verbose_name='关联计划'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AddField(
            model_name='assessmentmetric',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assessments.assessment', verbose_name='所属评估'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['therapist', 'customer'], name='idx_assess_therapist'),
        ),
    ]
