# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='assessments',
        ),
        migrations.AlterModelTable(
            name='assessmentmetric',
            table='assessment_metrics',
        ),
    ]
