# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_table_alter_assessmentmetric_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='tb_assessments',
        ),
        migrations.AlterModelTable(
            name='assessmentmetric',
            table='tb_assessment_metrics',
        ),
    ]
