# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_table_alter_assessmentmetric_table'),
        ('customers', '0004_alter_customer_therapist'),
        ('rehab', '0007_rename_course_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='rehab.rehabplan', verbose_name='关联计划'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='assessmentmetric',
            name='assessment',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assessments.assessment', verbose_name='所属评估'),
        ),
    ]
