# Generated by Django 6.0.8 on 2026-08-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('dashboard', '首页'), ('customer_detail', '客户详情'), ('lesson_preparation', '备课助手'), ('training_record', '训练记录'), ('assessment', '评估'), ('knowledge', '知识库'), ('general', '其他')], default='general', max_length=32, verbose_name='发起入口')),
                ('conversation_type', models.CharField(choices=[('general', '通用问答'), ('customer_discussion', '客户讨论'), ('preparation', '备课'), ('training', '训练'), ('assessment', '评估'), ('professional_question', '专业问答')], default='general', max_length=32, verbose_name='会话类型')),
                ('context_resource_type', models.CharField(blank=True, default='', max_length=32, verbose_name='关联资源类型')),
                ('context_resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='关联资源标识')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('status', models.CharField(choices=[('active', '进行中'), ('ended', '已结束')], default='active', max_length=12, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'db_table': 'tb_ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI 助手'), ('system', '系统'), ('tool', '工具')], max_length=12, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='会话')),
            ],
            options={
                'db_table': 'tb_ai_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['therapist', 'customer', 'status'], name='idx_conversation_scope'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['therapist', 'origin'], name='idx_conversation_origin'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_message_conversation'),
        ),
    ]
