# Generated by Django 6.0.8 on 2026-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summarized_through_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='摘要已覆盖到的消息 ID'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='摘要更新时间'),
        ),
    ]
