# Generated by Django 6.0.8 on 2026-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_summarized_through_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='episode_analyzed_through_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Episode 已分析到的消息 ID'),
        ),
    ]
