# Generated by Django 6.0.8 on 2026-08-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='客户姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('phone_masked', models.CharField(blank=True, default='', max_length=20, verbose_name='脱敏手机号')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('occupation', models.CharField(blank=True, default='', max_length=64, verbose_name='职业')),
                ('sport', models.CharField(blank=True, default='', max_length=64, verbose_name='运动项目')),
                ('main_issue', models.CharField(blank=True, default='', max_length=255, verbose_name='主要问题')),
                ('injury_date', models.DateField(blank=True, null=True, verbose_name='受伤日期')),
                ('surgery_date', models.DateField(blank=True, null=True, verbose_name='手术日期')),
                ('status', models.CharField(choices=[('active', '正常'), ('paused', '暂停'), ('closed', '结案')], default='active', max_length=10, verbose_name='状态')),
                ('first_visit_date', models.DateField(blank=True, null=True, verbose_name='首次到店日期')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='主负责康复师')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['therapist', 'status'], name='idx_customer_therapist_status'), models.Index(fields=['therapist', 'name'], name='idx_customer_therapist_name')],
            },
        ),
    ]
