# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tb_customers',
        ),
    ]
