# Generated by Django 6.0.8 on 2026-09-03 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, verbose_name='别称')),
                ('normalized_alias', models.CharField(max_length=64, verbose_name='规范化别称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='customer_aliases', to=settings.AUTH_USER_MODEL, verbose_name='归属康复师')),
            ],
            options={
                'verbose_name': '客户别称',
                'verbose_name_plural': '客户别称',
                'db_table': 'tb_customer_aliases',
                'indexes': [models.Index(fields=['therapist', 'normalized_alias'], name='idx_alias_therapist_norm')],
                'constraints': [models.UniqueConstraint(fields=('therapist', 'normalized_alias'), name='uniq_therapist_normalized_alias')],
            },
        ),
    ]
