# Generated by Django 6.0.8 on 2026-08-26 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('visit', '回访'), ('review', '复查'), ('other', '其他')], default='visit', max_length=12, verbose_name='类型')),
                ('due_date', models.DateField(verbose_name='计划日期')),
                ('content', models.CharField(blank=True, default='', max_length=255, verbose_name='内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('done', '已完成'), ('skipped', '已跳过')], default='pending', max_length=12, verbose_name='状态')),
                ('result', models.CharField(blank=True, default='', max_length=255, verbose_name='完成结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '回访/复查',
                'verbose_name_plural': '回访/复查',
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['therapist', 'due_date'], name='idx_followup_therapist')],
            },
        ),
    ]
