# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_alter_followuptask_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followuptask',
            table='tb_followup_tasks',
        ),
    ]
