# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        ('followups', '0003_alter_followuptask_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
    ]
