# Generated by Django 6.0.8 on 2026-08-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='上课日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('scheduled', '待上课'), ('completed', '已完成'), ('cancelled', '已取消'), ('absent', '请假')], default='scheduled', max_length=12, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'date'], name='idx_course_therapist_date'), models.Index(fields=['customer'], name='idx_course_customer')],
            },
        ),
    ]
