# Generated by Django 6.0.8 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    """为历史和新建课程增加可区分康复周期的课程主题。"""

    dependencies = [("schedules", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="course_name",
            field=models.CharField(default="康复训练", max_length=128, verbose_name="课程主题"),
        ),
    ]
