# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_coursesession_course_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursesession',
            table='course_sessions',
        ),
    ]
