# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_coursesession_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursesession',
            table='tb_course_sessions',
        ),
    ]
