# Generated by Django 6.0.8 on 2026-08-28 13:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseadjustment_delta_and_more'),
        ('customers', '0003_alter_customer_table'),
        ('rehab', '0003_alter_rehabplan_table_alter_rehabstage_table'),
        ('schedules', '0004_alter_coursesession_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='course_name',
            new_name='session_topic',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='session_count',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='课时单位'),
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程类型名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('default_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='默认时长（分钟）')),
                ('default_session_cost', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='默认单节课时消耗')),
                ('default_stage', models.CharField(blank=True, default='', max_length=12, verbose_name='默认适用阶段')),
                ('default_goals', models.TextField(blank=True, default='', verbose_name='默认课程目标')),
                ('default_notes', models.TextField(blank=True, default='', verbose_name='默认注意事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_types', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '课程类型',
                'verbose_name_plural': '课程类型',
                'db_table': 'tb_course_types',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(blank=True, default='', max_length=12, verbose_name='当前康复阶段')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=12, verbose_name='状态')),
                ('individual_goals', models.TextField(blank=True, default='', verbose_name='个体化目标')),
                ('planned_sessions', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='计划课次/课时')),
                ('session_cost', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='单节课时消耗快照')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='单节课时长（分钟）快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_courses', to='schedules.coursetype', verbose_name='课程类型')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_courses', to='customers.customer', verbose_name='客户')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_courses', to='courses.coursepackage', verbose_name='关联课时包')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_courses', to='rehab.rehabplan', verbose_name='关联康复计划')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_courses', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '客户疗程',
                'verbose_name_plural': '客户疗程',
                'db_table': 'tb_customer_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursesession',
            name='customer_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='schedules.customercourse', verbose_name='客户疗程'),
        ),
        migrations.AddIndex(
            model_name='coursetype',
            index=models.Index(fields=['therapist', 'is_active'], name='idx_coursetype_therapist'),
        ),
        migrations.AddIndex(
            model_name='customercourse',
            index=models.Index(fields=['therapist', 'customer'], name='idx_custcourse_therapist'),
        ),
        migrations.AddIndex(
            model_name='customercourse',
            index=models.Index(fields=['customer', 'status'], name='idx_custcourse_customer_status'),
        ),
    ]
