# Generated by Django 6.0.8 on 2026-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_coursesession_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='session_consumed',
            field=models.BooleanField(default=False, verbose_name='是否已扣课时'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='session_topic',
            field=models.CharField(default='康复训练', max_length=128, verbose_name='本节训练主题'),
        ),
    ]
