# Generated by Django 6.0.8 on 2026-08-29

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_alter_assessment_table_alter_assessmentmetric_table"),
        ("courses", "0004_alter_courseadjustment_delta_and_more"),
        ("rehab", "0004_rehabplan_end_date_rehabplan_goals"),
        ("schedules", "0006_coursesession_session_consumed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 旧“客户疗程”语义已废弃，且无需保留其数据或排课关联。
        migrations.RemoveField(
            model_name="coursesession",
            name="customer_course",
        ),
        migrations.DeleteModel(
            name="CustomerCourse",
        ),
        migrations.CreateModel(
            name="RehabPlanCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("paused", "暂停"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                ("goals", models.TextField(blank=True, default="", verbose_name="课程目标")),
                ("planned_count", models.PositiveIntegerField(default=1, verbose_name="计划次数")),
                (
                    "session_cost",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=4,
                        verbose_name="单节课时消耗快照",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="单节课时长（分钟）快照",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "course_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_courses",
                        to="schedules.coursetype",
                        verbose_name="课程类型",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_courses",
                        to="courses.coursepackage",
                        verbose_name="关联课时包",
                    ),
                ),
                (
                    "rehab_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_courses",
                        to="rehab.rehabplan",
                        verbose_name="康复周期计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "周期课程",
                "verbose_name_plural": "周期课程",
                "db_table": "tb_rehab_plan_courses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rehab_plan", "status"],
                        name="idx_plancourse_plan_status",
                    ),
                    models.Index(fields=["course_type"], name="idx_plancourse_type"),
                ],
            },
        ),
        migrations.AddField(
            model_name="coursesession",
            name="plan_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="schedules.rehabplancourse",
                verbose_name="周期课程",
            ),
        ),
        migrations.CreateModel(
            name="PlanCourseAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta_count", models.IntegerField(verbose_name="次数调整量")),
                ("before_count", models.PositiveIntegerField(verbose_name="调整前次数")),
                ("after_count", models.PositiveIntegerField(verbose_name="调整后次数")),
                ("reason", models.CharField(max_length=500, verbose_name="调整原因")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="调整时间")),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_course_adjustments",
                        to="assessments.assessment",
                        verbose_name="关联复评",
                    ),
                ),
                (
                    "plan_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="schedules.rehabplancourse",
                        verbose_name="周期课程",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_course_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作康复师",
                    ),
                ),
            ],
            options={
                "verbose_name": "周期课程次数调整",
                "verbose_name_plural": "周期课程次数调整",
                "db_table": "tb_plan_course_adjustments",
                "ordering": ["-created_at"],
            },
        ),
    ]
