# Generated by Django 6.0.8 on 2026-08-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0007_rename_course_plan_labels'),
        ('schedules', '0008_remove_coursetype_stage_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancourseadjustment',
            options={'ordering': ['-created_at'], 'verbose_name': '计划内课程次数调整', 'verbose_name_plural': '计划内课程次数调整'},
        ),
        migrations.AlterModelOptions(
            name='rehabplancourse',
            options={'ordering': ['-created_at'], 'verbose_name': '计划内课程', 'verbose_name_plural': '计划内课程'},
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='plan_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='schedules.rehabplancourse', verbose_name='计划内课程'),
        ),
        migrations.AlterField(
            model_name='plancourseadjustment',
            name='plan_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='schedules.rehabplancourse', verbose_name='计划内课程'),
        ),
        migrations.AlterField(
            model_name='rehabplancourse',
            name='rehab_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_courses', to='rehab.rehabplan', verbose_name='客户课程计划'),
        ),
    ]
