# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_customer_alter_assessment_plan_and_more'),
        ('courses', '0006_alter_courseadjustment_course_session_and_more'),
        ('customers', '0004_alter_customer_therapist'),
        ('rehab', '0008_alter_rehabplan_customer_and_more'),
        ('schedules', '0009_rename_course_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='plan_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='schedules.rehabplancourse', verbose_name='计划内课程'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_types', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='plancourseadjustment',
            name='assessment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_course_adjustments', to='assessments.assessment', verbose_name='关联复评'),
        ),
        migrations.AlterField(
            model_name='plancourseadjustment',
            name='plan_course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='schedules.rehabplancourse', verbose_name='计划内课程'),
        ),
        migrations.AlterField(
            model_name='plancourseadjustment',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='plan_course_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='操作康复师'),
        ),
        migrations.AlterField(
            model_name='rehabplancourse',
            name='course_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='plan_courses', to='schedules.coursetype', verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='rehabplancourse',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_courses', to='courses.coursepackage', verbose_name='关联课时包'),
        ),
        migrations.AlterField(
            model_name='rehabplancourse',
            name='rehab_plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='plan_courses', to='rehab.rehabplan', verbose_name='客户课程计划'),
        ),
    ]
