# Generated by Django 6.0.8 on 2026-08-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认康复计划', max_length=128, verbose_name='计划名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已结束')], default='active', max_length=12, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plans', to='customers.customer', verbose_name='客户')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plans', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '康复计划',
                'verbose_name_plural': '康复计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehabStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('acute', '急性期/疼痛控制'), ('recovery', '恢复期/活动度恢复'), ('strength', '力量重建期'), ('functional', '功能回归期')], max_length=12, verbose_name='阶段类型')),
                ('start_date', models.DateField(verbose_name='进入日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='阶段说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_stages', to='customers.customer', verbose_name='客户')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='rehab.rehabplan', verbose_name='所属计划')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_stages', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '康复阶段',
                'verbose_name_plural': '康复阶段',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rehabplan',
            index=models.Index(fields=['therapist', 'customer'], name='idx_rehabplan_therapist'),
        ),
        migrations.AddIndex(
            model_name='rehabstage',
            index=models.Index(fields=['customer', 'stage_type'], name='idx_rehabstage_customer'),
        ),
    ]
