# Generated by Django 6.0.8 on 2026-08-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rehabplan',
            table='rehab_plans',
        ),
        migrations.AlterModelTable(
            name='rehabstage',
            table='rehab_stages',
        ),
    ]
