# Generated by Django 6.0.8 on 2026-08-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_alter_rehabplan_table_alter_rehabstage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rehabplan',
            table='tb_rehab_plans',
        ),
        migrations.AlterModelTable(
            name='rehabstage',
            table='tb_rehab_stages',
        ),
    ]
