# Generated by Django 6.0.8 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rehab", "0003_alter_rehabplan_table_alter_rehabstage_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="rehabplan",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="rehabplan",
            name="goals",
            field=models.TextField(blank=True, default="", verbose_name="周期康复目标"),
        ),
    ]
