# Generated by Django 6.0.8 on 2026-08-30 11:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0005_stage_plan_constraints'),
        ('schedules', '0008_remove_coursetype_stage_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='适用说明')),
                ('suggested_duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='建议周期（周）')),
                ('goals', models.TextField(blank=True, default='', verbose_name='默认周期目标')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plan_templates', to=settings.AUTH_USER_MODEL, verbose_name='康复师')),
            ],
            options={
                'verbose_name': '康复周期模板',
                'verbose_name_plural': '康复周期模板',
                'db_table': 'tb_rehab_plan_templates',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rehabplan',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='rehab.rehabplantemplate', verbose_name='来源周期模板'),
        ),
        migrations.CreateModel(
            name='RehabPlanTemplateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_count', models.PositiveIntegerField(default=1, verbose_name='默认计划次数')),
                ('session_cost', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='默认单次课时扣减')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='默认单次时长（分钟）')),
                ('goals', models.TextField(blank=True, default='', verbose_name='默认课程目标')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rehab_plan_template_courses', to='schedules.coursetype', verbose_name='课程模板')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rehab.rehabplantemplate', verbose_name='康复周期模板')),
            ],
            options={
                'verbose_name': '康复周期模板课程',
                'verbose_name_plural': '康复周期模板课程',
                'db_table': 'tb_rehab_plan_template_courses',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='rehabplantemplate',
            index=models.Index(fields=['therapist', 'is_active'], name='idx_rpt_therapist_active'),
        ),
        migrations.AddConstraint(
            model_name='rehabplantemplatecourse',
            constraint=models.UniqueConstraint(fields=('template', 'course_type'), name='uniq_rpt_course_type'),
        ),
    ]
