# Generated by Django 6.0.8 on 2026-08-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0006_rehabplantemplate_rehabplan_source_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabplan',
            options={'ordering': ['-created_at'], 'verbose_name': '客户课程计划', 'verbose_name_plural': '客户课程计划'},
        ),
        migrations.AlterModelOptions(
            name='rehabplantemplate',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': '课程计划模板', 'verbose_name_plural': '课程计划模板'},
        ),
        migrations.AlterModelOptions(
            name='rehabplantemplatecourse',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '课程计划模板课程', 'verbose_name_plural': '课程计划模板课程'},
        ),
        migrations.AlterField(
            model_name='rehabplan',
            name='goals',
            field=models.TextField(blank=True, default='', verbose_name='计划目标'),
        ),
        migrations.AlterField(
            model_name='rehabplan',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='rehab.rehabplantemplate', verbose_name='来源课程计划模板'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplate',
            name='goals',
            field=models.TextField(blank=True, default='', verbose_name='默认计划目标'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplate',
            name='suggested_duration_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='建议时长（周）'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplatecourse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rehab.rehabplantemplate', verbose_name='课程计划模板'),
        ),
    ]
