# Generated by Django 6.0.8 on 2026-08-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_therapist'),
        ('rehab', '0007_rename_course_plan_labels'),
        ('schedules', '0009_rename_course_plan_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabplan',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plans', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='rehabplan',
            name='source_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='rehab.rehabplantemplate', verbose_name='来源课程计划模板'),
        ),
        migrations.AlterField(
            model_name='rehabplan',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plans', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplate',
            name='therapist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='rehab_plan_templates', to=settings.AUTH_USER_MODEL, verbose_name='康复师'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplatecourse',
            name='course_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='rehab_plan_template_courses', to='schedules.coursetype', verbose_name='课程模板'),
        ),
        migrations.AlterField(
            model_name='rehabplantemplatecourse',
            name='template',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rehab.rehabplantemplate', verbose_name='课程计划模板'),
        ),
        migrations.AlterField(
            model_name='rehabstage',
            name='plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='rehab.rehabplan', verbose_name='所属计划'),
        ),
    ]
